#!/usr/bin/env bash
# session-end.sh — Generate HANDOFF and close session
# Usage: ./session-end.sh --project "<name>" --summary "<summary>"

set -euo pipefail

PROJECT=""
SUMMARY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="$2"; shift 2 ;;
    --summary) SUMMARY="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ -z "$PROJECT" || -z "$SUMMARY" ]]; then
  echo "Usage: $0 --project \"<name>\" --summary \"<summary>\""
  exit 1
fi

DATE=$(date '+%Y-%m-%d %H:%M')
HANDOFF_DIR="projects/$PROJECT/.knowledge"
mkdir -p "$HANDOFF_DIR"

# Get git info
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
FILES=$(git diff --name-only 2>/dev/null | head -10 || echo "none")

# Generate HANDOFF
cat > "$HANDOFF_DIR/HANDOFF.md" << HANDOFF
# HANDOFF — $PROJECT

## Session Context
- **Date:** $DATE
- **Project:** $PROJECT
- **Branch:** $BRANCH

## Summary
$SUMMARY

## Files Changed
$FILES

## Next Steps
1. [ ]
2. [ ]

## Open Questions
- [ ]

---

*Generated by session-lifecycle workflow*
HANDOFF

# Update daily log
MEMORY_DIR="memory"
mkdir -p "$MEMORY_DIR"
SESSION_LOG="$MEMORY_DIR/$(date +%Y-%m-%d).md"

cat >> "$SESSION_LOG" << LOG

## Session End — $PROJECT
**End:** $DATE
**Summary:** $SUMMARY
**Branch:** $BRANCH

LOG

echo "✅ Session closed"
echo "   HANDOFF: $HANDOFF_DIR/HANDOFF.md"
echo "   Log: $SESSION_LOG"
echo ""

# Reflection prompt
echo "🤔 Quick reflection:"
echo "   ¿Qué aprendimos? ¿Algún patrón nuevo?"
echo "   ¿Es global (🌍) o de proyecto (🏗️)?"
echo "   Si hay algo, registrarlo en docs/LEARNINGS.md"
echo ""

# Check open PRs
echo "🔍 Checking open PRs..."
PR_SCRIPT="skills/oss-contribution/scripts/pr-status-check.sh"
if [[ -f "$PR_SCRIPT" ]]; then
  bash "$PR_SCRIPT" --author "$(gh api user --jq '.login' 2>/dev/null || echo "$USER")" 2>/dev/null || echo "   (no PRs or gh not available)"
fi
echo ""
echo "📋 Don't forget to:"
echo "   1. Review HANDOFF.md"
echo "   2. Commit workspace changes"
echo "   3. Push to remote"
