#!/usr/bin/env bash
# session-end.sh - Generate HANDOFF and close session
# Usage: ./session-end.sh --project "<name>" --summary "<summary>"

set -euo pipefail

PROJECT=""
SUMMARY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="$2"; shift 2 ;;
    --summary) SUMMARY="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ -z "$PROJECT" || -z "$SUMMARY" ]]; then
  echo "Usage: $0 --project \"<name>\" --summary \"<summary>\""
  exit 1
fi

DATE=$(date '+%Y-%m-%d %H:%M')
HANDOFF_DIR="projects/$PROJECT/.knowledge"
mkdir -p "$HANDOFF_DIR"

# Get git info
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
FILES=$(git diff --name-only 2>/dev/null | head -10 || echo "none")

# Generate HANDOFF
cat > "$HANDOFF_DIR/HANDOFF.md" << HANDOFF
# HANDOFF - $PROJECT

## Session Context
- **Date:** $DATE
- **Project:** $PROJECT
- **Branch:** $BRANCH

## Summary
$SUMMARY

## Files Changed
$FILES

## Next Steps
1. [ ]
2. [ ]

## Open Questions
- [ ]

---

*Generated by session-lifecycle workflow*
HANDOFF

# Update daily log - DB-first (2026-08-31)
# The DB (memory.db) is the source of truth; the .md is a regenerable view.
MEMORY_DIR="memory"
mkdir -p "$MEMORY_DIR"
SESSION_LOG="$MEMORY_DIR/$(date +%Y-%m-%d).md"

# Recover the complexity T-score recorded at session start for a clean record
TSCORE_LINE=""
if grep -q "^## $PROJECT$" "$SESSION_LOG" 2>/dev/null; then
  TSCORE_LINE=$(grep -A3 "^## $PROJECT$" "$SESSION_LOG" 2>/dev/null | grep -oE "\*\*Complexity T-score:\*\* .*" | head -1)
fi

# Write to DB as source of truth, then regenerate the .md view
if command -v python3 >/dev/null 2>&1 && [ -f "scripts/memory-end-session.py" ]; then
  python3 scripts/memory-end-session.py \
    --project "$PROJECT" \
    --summary "$SUMMARY" \
    --branch "$BRANCH" \
    --tscore "$TSCORE_LINE" \
    --skip-catalog || echo "   ⚠️  Fallback: session-end DB write failed"
else
  # Fallback to the old direct .md append if the DB-first script is unavailable
  cat >> "$SESSION_LOG" << LOG

## Session End - $PROJECT
**End:** ${DATE}
**Summary:** $SUMMARY
**Branch:** $BRANCH
LOG
fi

echo "✅ Session closed"
echo "   HANDOFF: $HANDOFF_DIR/HANDOFF.md"
echo "   Log: $SESSION_LOG"
echo ""

# Auto-catalog memory into relational DB + embeddings (2026-08-30)
# Keeps memory.db always in sync with the daily notes without manual runs.
if command -v python3 >/dev/null 2>&1 && [ -f "scripts/memory-catalog-v2.py" ]; then
  echo "🗂️  Cataloging memory into DB..."
  python3 "scripts/memory-catalog-v2.py" >/dev/null 2>&1 && echo "   ✅ Memory cataloged" || echo "   ⚠️  Catalog skipped (see error above)"
else
  echo "   ⚠️  memory-catalog-v2.py not found - skip cataloging"
fi
echo ""

# Reflection prompt
# Post-task reflection (2026-09-03): automatic post-task reflection stage.
# Complements the closing self-reflection: this one runs per task, not per session.
# Usage: ./scripts/post-task-reflection.sh --type <type> --summary "..." [--check-dups --propose-skill --save]
if [[ -x "scripts/post-task-reflection.sh" ]]; then
  echo "🤔 Post-task reflection available:"
  echo "   ./scripts/post-task-reflection.sh --type <debug|feature|review|config|research|oss|docs|other> \\"
  echo "       --summary \"<what happened>\" --lesson \"<lesson>\" --check-dups --propose-skill --save"
  echo "   (run it per complex task, not only when closing a session)"
  echo ""
fi
# Closing self-reflection (global learnings)
echo "🤔 Quick reflection:"
echo "   What did we learn? Any new pattern?"
echo "   Is it global (🌍) or project-specific (🏗️)?"
echo "   If there is something, record it in docs/LEARNINGS.md"
echo ""
# PRs (2026-08-25): the user reviews them manually on GitHub and passes the URLs to review.
# PRs are not checked automatically when closing a session.
echo "📋 Don't forget to:"
echo "   1. Review HANDOFF.md"
echo "   2. Commit workspace changes"
echo "   3. Push to remote"
