#!/usr/bin/env python3
"""generate-governance-report.py — Compile GOVERNANCE_REPORT.md from audit outputs.

Usage:
  python3 generate-governance-report.py [--audit <audit-file>] [--duplicates <duplicates-file>] [--output <file>]

Combines workflow audit results, duplicate detection, and metrics into
a single governance report.
"""

import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime


def run_workflow_audit(skills_dir: str) -> dict:
    """Run workflow-audit.sh and capture results."""
    result = subprocess.run(
        ["bash", "scripts/workflow-audit.sh", "--output", "/tmp/_audit_temp.md"],
        capture_output=True,
        text=True,
        cwd=skills_dir,
    )
    return {"stdout": result.stdout, "report_path": "/tmp/_audit_temp.md"}


def run_duplicate_detection(skills_dir: str) -> dict:
    """Run detect-duplicates.sh and capture results."""
    result = subprocess.run(
        ["bash", "scripts/detect-duplicates.sh", "--output", "/tmp/_dupes_temp.md"],
        capture_output=True,
        text=True,
        cwd=skills_dir,
    )
    return {"stdout": result.stdout, "report_path": "/tmp/_dupes_temp.md"}


def count_skills(skills_dir: str) -> int:
    """Count skills in the workspace."""
    skills_path = Path(skills_dir)
    return len([d for d in skills_path.iterdir() if d.is_dir() and (d / "SKILL.md").exists()])


def count_total_references(skills_dir: str) -> int:
    """Count total reference files across all skills."""
    skills_path = Path(skills_dir)
    count = 0
    for skill_dir in skills_path.iterdir():
        if skill_dir.is_dir():
            ref_dir = skill_dir / "references"
            if ref_dir.exists():
                count += len(list(ref_dir.glob("*.md")))
    return count


def count_total_scripts(skills_dir: str) -> int:
    """Count total script files across all skills."""
    skills_path = Path(skills_dir)
    count = 0
    for skill_dir in skills_path.iterdir():
        if skill_dir.is_dir():
            scripts_dir = skill_dir / "scripts"
            if scripts_dir.exists():
                count += len([f for f in scripts_dir.iterdir() if f.is_file()])
    return count


def main():
    skills_dir = str(Path(__file__).parent.parent.parent)
    output_file = "GOVERNANCE_REPORT.md"

    # Parse args
    args = sys.argv[1:]
    while args:
        if args[0] == "--output" and len(args) > 1:
            output_file = args[1]
            args = args[2:]
        else:
            args = args[1:]

    # Gather metrics
    skill_count = count_skills(skills_dir)
    ref_count = count_total_references(skills_dir)
    script_count = count_total_scripts(skills_dir)

    # Generate report
    report = f"""# Governance Report

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

## System Overview

| Metric | Value |
|--------|-------|
| Total Skills | {skill_count} |
| Total References | {ref_count} |
| Total Scripts | {script_count} |
| Avg References/Skill | {ref_count / max(skill_count, 1):.1f} |
| Avg Scripts/Skill | {script_count / max(skill_count, 1):.1f} |

## Skills Without References

"""

    # Find skills without references
    skills_path = Path(skills_dir)
    for skill_dir in sorted(skills_path.iterdir()):
        if not skill_dir.is_dir():
            continue
        ref_dir = skill_dir / "references"
        scripts_dir = skill_dir / "scripts"
        has_refs = ref_dir.exists() and len(list(ref_dir.glob("*.md"))) > 0
        has_scripts = scripts_dir.exists() and len([f for f in scripts_dir.iterdir() if f.is_file()]) > 0

        if not has_refs or not has_scripts:
            report += f"- **{skill_dir.name}:** "
            if not has_refs:
                report += "no references "
            if not has_scripts:
                report += "no scripts "
            report += "\n"

    report += """
## Recommendations

1. **Prioritize adding references** to skills that lack them
2. **Add automation scripts** to skills with manual-only workflows
3. **Review duplicate content** for potential extraction into shared references
4. **Consider merging** skills with overlapping responsibilities

---

*Generated by engineering-governance workflow*
"""

    Path(output_file).write_text(report)
    print(f"✅ Governance report generated: {output_file}")


if __name__ == "__main__":
    main()
