#!/usr/bin/env bash
# generate-adr.sh — Create a new ADR
# Usage: ./generate-adr.sh --title "<title>" --status proposed|accepted

set -euo pipefail

TITLE=""
STATUS="proposed"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title) TITLE="$2"; shift 2 ;;
    --status) STATUS="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ -z "$TITLE" ]]; then
  echo "Usage: $0 --title \"<title>\" [--status proposed|accepted]"
  exit 1
fi

# Find next ADR number
ADR_DIR="docs/adr"
mkdir -p "$ADR_DIR"

# Use sed instead of grep -oP (macOS BSD grep doesn't support -P)
LAST=$(ls "$ADR_DIR"/*.md 2>/dev/null | sort | tail -1 | sed -E 's/.*\/([0-9]+)-.*/\1/' || echo "0")
NEXT=$((10#$LAST + 1))
NUM=$(printf "%03d" "$NEXT")

SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
FILE="$ADR_DIR/$NUM-$SLUG.md"

cat > "$FILE" << ADR
# ADR-$NUM: $TITLE

**Status:** $STATUS
**Date:** $(date '+%Y-%m-%d')

## Context
[What's the problem? What constraints exist?]

## Decision
[What did we decide?]

## Consequences
- **Positive:** [benefits]
- **Negative:** [trade-offs]
- **Risks:** [risks to monitor]

## Alternatives Considered
- **Alternative A:** [why not]
- **Alternative B:** [why not]

---

*Generated by tech-docs workflow*
ADR

echo "✅ ADR created: $FILE"
